builds:
- id: twitterview
  binary: twitterview
  main: ./cmd/twitterview
  goos:   [ linux ]
  goarch: [ amd64 ]
  flags:  [ -v ]
- id: hackerview
  binary: hackerview
  main: ./cmd/hackerview
  goos:   [ linux ]
  goarch: [ amd64 ]
  flags:  [ -v ]
