builds:

  - id: twitterview
    binary: twitterview
    main: ./cmd/twitterview
    goos:    [  linux  ]
    goarch:  [  amd64  ]
    ldflags: [ "-s -w" ]

  - id: hackerview
    binary: hackerview
    main: ./cmd/hackerview
    goos:    [  linux  ]
    goarch:  [  amd64  ]
    ldflags: [ "-s -w" ]

  - id: redditview
    binary: redditview
    main: ./cmd/redditview
    goos:    [  linux  ]
    goarch:  [  amd64  ]
    ldflags: [ "-s -w" ]

  - id: fourchanview
    binary: fourchanview
    main: ./cmd/fourchanview
    goos:    [  linux  ]
    goarch:  [  amd64  ]
    ldflags: [ "-s -w" ]

  - id: vichanview
    binary: vichanview
    main: ./cmd/vichanview
    goos:    [  linux  ]
    goarch:  [  amd64  ]
    ldflags: [ "-s -w" ]

  - id: discourseview
    binary: discourseview
    main: ./cmd/discourseview
    goos:    [  linux  ]
    goarch:  [  amd64  ]
    ldflags: [ "-s -w" ]

  - id: lobstersview
    binary: lobstersview
    main: ./cmd/lobstersview
    goos:    [  linux  ]
    goarch:  [  amd64  ]
    ldflags: [ "-s -w" ]
