HN_URL := 'https://news.ycombinator.com/item?id=3078128'
TW_URL := 'https://twitter.com/TwitterDev/status/1443269993676763138'

.PHONY: all test build clean install

all: test build
build:   ; go build -x -v ./...
clean:   ; go clean -x ./...
install: ; go install ./...
test:
	go vet ./...
	go test ./...
#	go run cmd/hackerview/main.go -t 20s $(HN_URL)
	go run cmd/twitterview/main.go -t 20s $(TW_URL)
