GO ?= /usr/bin/go
HN_URL := 'https://news.ycombinator.com/item?id=3078128'
TW_URL := 'https://twitter.com/TwitterDev/status/1443269993676763138'

.PHONY: all test build clean install

all: test build
build:   ; $(GO) build -x -v ./...
clean:   ; $(GO) clean -x ./...
install: ; $(GO) install ./...
test:
	$(GO) vet ./...
	$(GO) test ./...
#	$(GO) run cmd/hackerview/main.go -t 20s $(HN_URL)
	$(GO) run cmd/twitterview/main.go -t 20s $(TW_URL)
