name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - run: go test ./...
      - run: |
          go run cmd/hackerview/main.go -t 20s https://news.ycombinator.com/item?id=3078128
          go run cmd/twitterview/main.go -t 20s https://twitter.com/TwitterDev/status/1443269993676763138
