name: CI

on:

  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.org'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - run: |
          make test
